apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend
spec:
  ingressClassName: "nginx"
  rules:
  - host: todoapp.com
    http:
      paths:
        - backend:
            serviceName: frontend
            servicePort: 8080
